export default {
    notifications: [],
    role:"",
    permissions:[],
    roles:[],
    vrole:{},
    users:[],
    vuser:{},
    bootcamps:[],
    vbootcamp:{},
    flowsteps:[],
    vflowstep:{},
    employers:[],
    vemployer:{},
    profiles:[],
    vprofile:{},
    applications:[],
    vapplication:{},
    jobs:[],
    vjob:{},
    ecosystem_users:[],
    summary_employing:{},
    report_employing:[],
    jobboard_report:{},
    quizzes: [],
    vquizz: {}
}